
language: cpp
compiler: gcc
dist: trusty
matrix:
  include:
    - env: JOB=1
    - env: JOB=2
    - env: JOB=3
    - env: JOB=4
    - env: JOB=5
    - env: JOB=6
    - env: JOB=7
    - env: JOB=8
    - env: JOB=9
    - env: JOB=10
    - env: JOB=11
    - env: JOB=12
    - env: JOB=13
    - env: JOB=14
    - env: JOB=15
    - env: JOB=16
    - env: JOB=17
    - env: JOB=18
    - env: JOB=19
    - env: JOB=20
    - env: JOB=21
    - env: JOB=22
    - env: JOB=23
    - env: JOB=24
script:
- sudo ./run.sh $JOB
